<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>11.0</LangVersion>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <DocumentationFile></DocumentationFile>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="ModShardLauncher">
      <HintPath>..\..\ModShardLauncher.dll</HintPath>
    </Reference>
    <Reference Include="UndertaleModLib">
      <HintPath>..\..\UndertaleModLib.dll</HintPath>
    </Reference>
  </ItemGroup>
  
</Project>
