Arcane_Damage;;Arcane;秘法;;;;;;;;;;
Piercing_Damage;;Piercing;刺骨;;;;;;;;;;
Sacred_Damage;;Sacred;圣洁;;;;;;;;;;
Unholy_Damage;;Unholy;邪能;;;;;;;;;;
Psionic_Damage;;Psionic;冥思;;;;;;;;;;
STR;;Strength;英勇;;;;;;;;;;
AGL;;Agility;迅捷;;;;;;;;;;
PRC;;Perception;直觉;;;;;;;;;;
Vitality;;Vitality;生机;;;;;;;;;;
WIL;;Will;智慧;;;;;;;;;;
Miracle_Chance;;Miracle Chance;辉流;;;;;;;;;;
Miracle_Power;;Miracle Power;奥法;;;;;;;;;;
