function table_surface_spawn()
{
    return [
        "Slot;Tier;Biome;Faction;Spawn_Chance;Enemy1;Enemy2;Enemy3;Enemy4;Enemy5;Enemy6;",

        // ==================== 野兽 (Beast) 森林与松木林 ====================
        "Hostile;1, 2, 3, 4, 5;Forest, Pineforest;Beast;10;o_wolf;o_wolf;;;;;",
        "Hostile;2, 3, 4, 5;Forest, Pineforest;Beast;10;o_wolf;o_wolf;o_wolf;;;;",
        "Hostile;3, 4, 5;Forest, Pineforest;Beast;5;o_wolf;o_wolf;o_wolf;o_wolf;;;",
        "Hostile;3, 4, 5;Forest, Pineforest;Beast;5;o_wolf;o_wolf;;o_wolf;o_wolf;;",
        "Hostile;4, 5;Forest, Pineforest;Beast;5;o_wolf;o_wolf;o_wolf;o_wolf;o_wolf;o_wolf;",
        "Hostile;1, 2, 3, 4, 5;Forest, Pineforest;Beast;6;o_bear;;;;;;",
        "Hostile;1, 2, 3, 4, 5;Forest, Pineforest;Beast;5;o_moose;;;;;;",
        "Hostile;1, 2, 3, 4, 5;Forest, Pineforest;Beast;15;o_boar;;;;;;",
        "Hostile;2, 3, 4, 5;Forest, Pineforest;Beast;10;o_boar;o_boar;;;;;",
        "Hostile;3, 4, 5;Forest, Pineforest;Beast;5;o_boar;o_boar;o_boar;;;;",
        "Hostile;2, 3, 4, 5;Forest, Pineforest;Beast;1;o_small_troll;;;;;;",
        "Hostile;3, 4, 5;Forest, Pineforest;Beast;2;o_small_troll;;;;;;",
        "Hostile;5;Forest, Pineforest;Beast;2;o_small_troll;o_small_troll;;;;;",
        "Neutral;1, 2, 3, 4, 5;Forest, Pineforest;Beast;20;o_fox;;;;;;",
        "Neutral;1, 2, 3, 4, 5;Forest, Pineforest;Beast;30;o_hedgehog;;;;;;",
        "Neutral;1, 2, 3, 4, 5;Forest, Pineforest;Beast;30;o_squirrel;;;;;;",
        "Neutral;1, 2, 3, 4, 5;Forest, Pineforest;Beast;30;o_deer_m;o_deer_w;;;;;",
        "Neutral;1, 2, 3, 4, 5;Forest, Pineforest;Beast;20;o_deer_m;o_deer_w;o_deer_w;;;;",

        // ==================== 野兽 (Beast) 草地与平原 ====================
        "Hostile;1;Field, Pinefield;Beast;15;o_wild_dog;o_wild_dog;;;;;",
        "Hostile;1, 2;Field, Pinefield;Beast;10;o_wild_dog;o_wild_dog;o_wild_dog;;;;",
        "Hostile;2;Field, Pinefield;Beast;5;o_wild_dog;o_wild_dog;o_wild_dog;o_wild_dog;;;",
        "Hostile;1, 2, 3, 4, 5;Pinefield;Beast;10;o_wolf;o_wolf;;;;;",
        "Hostile;2, 3, 4, 5;Pinefield;Beast;7;o_wolf;o_wolf;o_wolf;;;;",
        "Hostile;3, 4, 5;Pinefield;Beast;5;o_wolf;o_wolf;o_wolf;o_wolf;;;",
        "Hostile;3, 4, 5;Pinefield;Beast;3;o_wolf;o_wolf;o_wolf;o_wolf;o_wolf;o_wolf;",
        "Hostile;1, 2, 3, 4, 5;Pinefield;Beast;6;o_bear;;;;;;",
        "Hostile;1, 2, 3, 4, 5;Pinefield;Beast;4;o_moose;;;;;;",
        "Hostile;1, 2, 3, 4, 5;Pinefield;Beast;10;o_boar;;;;;;",
        "Hostile;3, 4, 5;Pinefield;Beast;5;o_boar;o_boar;;;;;",
        "Hostile;4, 5;Pinefield;Beast;2;o_small_troll;;;;;;",
        "Hostile;5;Pinefield;Beast;1;o_small_troll;o_small_troll;;;;;",
        "Neutral;1, 2, 3, 4, 5;Field, Pinefield;Beast;35;o_hedgehog;;;;;;",
        "Neutral;1, 2, 3, 4, 5;Field, Pinefield;Beast;50;o_bunny;;;;;;",
        "Neutral;1, 2, 3, 4, 5;Field, Pinefield;Beast;20;o_bunny;o_bunny;;;;;",

        // ==================== 野兽 (Beast) 荒漠/草原 (Steppe) ====================
        "Hostile;3, 4, 5;Steppe;Beast;1;o_gulon;;;;;;",
        "Hostile;4, 5;Steppe;Beast;6;o_gulon;;;;;;",
        "Hostile;4, 5;Steppe;Beast;4;o_gulon;o_gulon;;;;;",
        "Hostile;5;Steppe;Beast;2;o_gulon;o_gulon;o_gulon;;;;",
        "Hostile;3, 4;Steppe;Beast;5;o_harpy;;;;;;",
        "Hostile;3, 4, 5;Steppe;Beast;5;o_harpy;o_harpy;;;;;",
        "Hostile;4, 5;Steppe;Beast;4;o_harpy;o_harpy;o_harpy;;;;",
        "Hostile;5;Steppe;Beast;3;o_harpy;o_harpy;o_harpy;o_harpy;;;",
        "Hostile;1, 2, 3, 4, 5;Steppe;Beast;12;o_bison;o_bison;;;;;",
        "Hostile;1, 2, 3, 4, 5;Steppe;Beast;9;o_bison;o_bison;o_bison;;;;",
        "Hostile;1, 2, 3, 4, 5;Steppe;Beast;6;o_bison;o_bison;o_bison;o_bison;;;",
        "Hostile;1, 2, 3, 4, 5;Steppe;Beast;3;o_bison;o_bison;o_bison;o_bison;o_bison;;",
        "Neutral;1, 2, 3, 4, 5;Steppe;Beast;40;o_bunny;;;;;;",
        "Neutral;1, 2, 3, 4, 5;Steppe;Beast;15;o_bunny;o_bunny;;;;;",
        "Neutral;1, 2, 3, 4, 5;Steppe;Beast;25;o_saiga_m;;;;;;",
        "Neutral;1, 2, 3, 4, 5;Steppe;Beast;25;o_saiga_w;;;;;;",
        "Neutral;1, 2, 3, 4, 5;Steppe;Beast;20;o_saiga_m;o_saiga_w;;;;;",
        "Neutral;1, 2, 3, 4, 5;Steppe;Beast;15;o_saiga_m;o_saiga_w;o_saiga_w;;;;",
        "Neutral;1, 2, 3, 4, 5;Steppe;Beast;10;o_saiga_m;o_saiga_m;o_saiga_w;o_saiga_w;;;",

        // ==================== 土匪 Boss 精英小队 ====================
        "Hostile;1;Any;Brigand;5;Fighter, Assassin, Ranger;Fighter, Tank, Mage;o_bandit_kingpin;;;;",
        "Hostile;1;Any;Brigand;5;Fighter;Fighter, Tank, Expendable;o_bandit_madman;;;;",
        "Hostile;1;Any;Brigand;5;Fighter, Tank;Ranger, Expendable, Support, Mage;o_bandit_overseer;;;;",
        "Hostile;2;Any;Brigand;5;Fighter, Assassin, Ranger;Fighter, Tank, Mage;o_bandit_firestarter;;;;",
        "Hostile;2;Any;Brigand;5;Fighter, Tank;Ranger, Expendable, Support, Mage;o_bandit_raider;;;;",
        "Hostile;3;Any;Brigand;15;Fighter;Fighter, Tank;Fighter, Assassin, Ranger;o_bandit_warlock;;;",
        "Hostile;3;Any;Brigand;15;Fighter;Fighter, Tank;Fighter, Assassin, Ranger;o_bandit_bonebreaker_axe;;;",
        "Hostile;3;Any;Brigand;15;Fighter;Fighter, Tank;Fighter, Assassin, Ranger;o_bandit_bonebreaker_mace;;;",
        "Hostile;3;Any;Brigand;15;Fighter;Fighter, Tank;Fighter, Assassin, Ranger;o_bandit_torturer;;;",
        "Hostile;4;Any;Brigand;12;Fighter, Ranger;Fighter, Assassin, Mage;Fighter, Tank;o_bandit_huntmaster;;",
        "Hostile;4;Any;Brigand;12;Fighter, Ranger;Fighter, Assassin, Mage;Fighter, Tank;o_bandit_paymaster;;",
        "Hostile;4;Any;Brigand;12;Fighter, Tank;Fighter, Assassin, Ranger;Fighter, Ranger, Mage;o_bandit_condottiere;;",
        "Hostile;5;Any;Brigand;5;Fighter;Fighter, Tank;Fighter, Assassin, Ranger, Mage;Ranger, Mage, Support;o_bandit_arcanist;",
        "Hostile;5;Any;Brigand;5;Fighter;Fighter, Tank;Fighter, Assassin, Ranger, Mage;Ranger, Mage, Support;o_bandit_raubritter_2hsword;",
        "Hostile;5;Any;Brigand;5;Fighter;Fighter, Tank;Fighter, Assassin, Ranger, Mage;Ranger, Mage, Support;o_bandit_raubritter_2hmace;",
        "Hostile;5;Any;Brigand;5;Fighter;Fighter, Tank;Fighter, Assassin, Ranger, Mage;Ranger, Mage, Support;o_bandit_raubritter_flail;",
        "Hostile;5;Any;Brigand;5;Fighter;Fighter, Tank;Fighter, Assassin, Ranger, Mage;Ranger, Mage, Support;o_bandit_witchhunter;",

        // ==================== 亡灵 Boss 精英小队 ====================
        "Hostile;1;Any;Undead;5;Expendable;Expendable, Fighter;o_occultist;;;;",
        "Hostile;2;Any;Undead;5;Fighter;Ranger, Mage;Expendable;o_archivist;;;",
        "Hostile;2;Any;Undead;5;Fighter, Assassin;Fighter, Tank;Support, Mage;o_necromancer;;;",
        "Hostile;3;Any;Undead;15;Assassin, Fighter;Mage;Support;o_armored_husk;;;",
        "Hostile;3;Any;Undead;15;Assassin, Fighter;Mage;Support;o_undertaker;;;",
        "Hostile;3;Any;Undead;15;Assassin, Fighter;Mage;Support;o_ritualist;;;",
        "Hostile;4;Any;Undead;8;Tank, Fighter;Assassin;Mage, Support;o_crypt_warden;;;",
        "Hostile;4;Any;Undead;8;Tank, Fighter;Assassin;Mage, Support;o_restless_hero;;;",
        "Hostile;4;Any;Undead;8;Tank, Fighter;Assassin;Mage, Support;o_mortician;;;",
        "Hostile;5;Any;Undead;5;Fighter, Tank;Assassin, Fighter;Mage;Mage, Support;o_revenant;",
        "Hostile;5;Any;Undead;5;Fighter, Tank;Assassin, Fighter;Mage;Mage, Support;o_spectral_herald;",
        "Hostile;5;Any;Undead;5;Fighter, Tank;Assassin, Fighter;Mage;Mage, Support;o_wraithbinder;",


        // ==================== 变节信徒 Boss 精英小队 ====================
        "Hostile;1;Any;Vampire;5;Fighter;Expendable, Fighter;o_proselyte_apostate;;;;",
        "Hostile;1;Any;Vampire;5;Fighter;Expendable, Fighter;o_proselyte_abomination;;;;",
        "Hostile;2;Any;Vampire;5;Fighter;Assassin;Mage, Support;o_proselyte_matriarch;;;",
        "Hostile;2;Any;Vampire;5;Fighter, Tank;Ranger;Support;Expendable;o_proselyte_seer;;;",
        "Hostile;3;Any;Vampire;15;Tank, Fighter;Ranger;Mage, Support;o_proselyte_brander;;;",
        "Hostile;3;Any;Vampire;15;Tank, Fighter;Ranger;Mage, Support;o_proselyte_admonisher;;;",
        "Hostile;3;Any;Vampire;15;Tank, Fighter;Ranger;Mage, Support;o_proselyte_begotten;;;",
        "Hostile;4;Any;Vampire;8;Tank;Fighter, Assassin;Mage;Support;o_proselyte_anmarrak;;;",
        "Hostile;4;Any;Vampire;8;Tank;Fighter, Assassin;Mage;Support;o_proselyte_juggernaut;;;",
        "Hostile;4;Any;Vampire;8;Tank;Fighter, Assassin;Mage;Support;o_proselyte_wormbearer;;;",
        "Hostile;5;Any;Vampire;5;Assassin, Fighter;Mage;Support;Tank;o_proselyte_nakkatar;",
        "Hostile;5;Any;Vampire;5;Assassin, Fighter;Mage;Support;Tank;o_proselyte_apostle;",
        "Hostile;5;Any;Vampire;5;Assassin, Fighter;Mage;Support;Tank;o_proselyte_leechlord;",

        // ==================== 全Boss特殊小队 ====================
        "Hostile;3;Any;Brigand;2;o_bandit_warlock;o_bandit_bonebreaker_axe;o_bandit_bonebreaker_mace;o_bandit_torturer;;;",
        "Hostile;4;Any;Brigand;2;o_bandit_huntmaster;o_bandit_paymaster;o_bandit_condottiere;;;;",
        "Hostile;5;Any;Brigand;1;o_bandit_arcanist;o_bandit_raubritter_2hsword;o_bandit_raubritter_2hmace;o_bandit_raubritter_flail;o_bandit_witchhunter;",
        "Hostile;3;Any;Undead;2;o_armored_husk;o_undertaker;o_ritualist;;;;",
        "Hostile;4;Any;Undead;2;o_crypt_warden;o_restless_hero;o_mortician;;;;",
        "Hostile;5;Any;Undead;1;o_revenant;o_spectral_herald;o_wraithbinder;;;;",
        "Hostile;3;Any;Vampire;2;o_proselyte_brander;o_proselyte_admonisher;o_proselyte_begotten;;;;",
        "Hostile;4;Any;Vampire;2;o_proselyte_anmarrak;o_proselyte_juggernaut;o_proselyte_wormbearer;;;;",
        "Hostile;5;Any;Vampire;1;o_proselyte_nakkatar;o_proselyte_apostle;o_proselyte_leechlord;;;;",

        // ==================== 野兽精英小队 ====================
        "Hostile;5;Any;Beast;4;o_small_troll;o_small_troll;o_small_troll;o_small_troll;;;"
    ];
}