event_inherited();
ds_list_clear(myfloor_list);
ds_list_add(myfloor_list, "S1", "S1", "S1", "S1");
occupation = "darrel";
show_town = false;
name = ds_list_find_value(global.npc_constant_name, 84);
is_follower = true;
scr_buying_loot_category("alcohol", "armor", "medicine", "beverage", "potion", "jewelry", "food", "tool", "weapon", "scroll", "valuable", "drug", "scroll", "junk", "ingredient", "curse", "herb", "bag", "book", "backpack", "additive", "treatise", "treasure", "upgrade", "ammo", "material", "recipe", "schematic", "comm_wheat", "comm_ale", "comm_wine", "comm_cider", "comm_timber", "comm_coal", "comm_salt");
scr_npc_gold_init(14500, 17500);
Selling_Prices = 1;
Buying_Prices += 0.2;
Material_Spec = ["all"];
can_repair = true;
Repair_Prices_Base = 0.8;
can_trade_array = [1, 1, 1, 1];
trade_tags = "aldor common";
time_period_night = do_animation;
chat = false;
quit_location = "r_DocksTavern01floor";
quit_target = o_npc_target_caravan_darrel_quit;
trade_target = o_npc_target_caravan_darrel_trading;
dialog_id = "master_caravan";
scr_create_skill_map("Onslaught");
scr_create_skill_map("Armor_Break");
scr_create_skill_map("Sweep");
scr_create_skill_map("Power_Kick");
scr_enemy_create_invisible_consum(o_b_mobBandage, 40, choose(1, 2));
scr_enemy_create_invisible_consum(o_b_mobSplint, 25, choose(1, 2));
scr_enemy_create_invisible_consum(o_b_mobEssence, 5, 1);
is_quest = true;
ai_script = scr_enemy_choose_state;
Restock_Time = 6;
